spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 124905365987-tk4l4gg6e2lu5kc89bpa16qjudogv6pb.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Avionix Gateway Server Application"
    version: "1.0"

logging:
  level:
    avia:
      cloud:
        gatewayserver: DEBUG
    org:
      springframework:
        security: DEBUG