services:

  configserver:
    image: "adpsorcerer/avionix-configserver:r1"
    container_name: configserver
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "adpsorcerer/avionix-eurekaserver:r1"
    container_name: eurekaserver
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  discovery:
    image: "adpsorcerer/avionix-discovery:r1"
    container_name: discovery
    ports:
      - "9000:9000"
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "discovery"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  client:
    image: "adpsorcerer/avionix-client:r1"
    container_name: client
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      discovery:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "client"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  flight:
    image: "adpsorcerer/avionix-flight:r1"
    container_name: flight
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      client:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "flight"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  gatewayserver:
    image: "adpsorcerer/avionix-gatewayserver:r1"
    container_name: gatewayserver
    ports:
      - "8072:8072"
    depends_on:
      flight:
        condition: service_healthy
      client:
        condition: service_healthy
      discovery:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  avionix:
    driver: "bridge"