spring:
  application:
    name: "flight"
  profiles:
    active: "default"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    stream:
      bindings:
        sendHtmlMessage-out-0:
          destination: send-html-message
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "flight"
    description: "Avionix Flight Application"
    version: "1.0"

logging:
  level:
    avia:
      cloud:
        booking: DEBUG
    org:
      springframework:
        security: DEBUG

stripe:
  secret_key: "sk_test_51P0N25HNHJlsfXUE4645pCTuNcVPG2TgPYOMEWZTggtLviyY3SwiFUROMz357c8XrerbcZsFSYlSTFLesRR5519h00wvDfj979"
