apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: "adpsorcerer/avionix-client:r1.f"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: avionix-configmap
              key: CLIENT_APPLICATION_NAME
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: avionix-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: avionix-configmap
              key: SPRING_RABBITMQ_HOST
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: avionix-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: avionix-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  selector:
    app: client
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
