apiVersion: v1
kind: ConfigMap
metadata:
  name: avionix-configmap
data:
  SPRING_PROFILES_ACTIVE: "default"
  SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
  CONFIGSERVER_APPLICATION_NAME: "configserver"
  EUREKA_APPLICATION_NAME: "eurekaserver"
  CLIENT_APPLICATION_NAME: "client"
  DISCOVERY_APPLICATION_NAME: "discovery"
  FLIGHT_APPLICATION_NAME: "flight"
  GATEWAY_APPLICATION_NAME: "gatewayserver"
  MESSAGE_APPLICATION_NAME: "message"
  SPRING_RABBITMQ_HOST: "rabbitmq"
