spring:
  application:
    name: "discovery"
  profiles:
    active: "default"
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "discovery"
    description: "Avionix Discovery Application"
    version: "1.0"

logging:
  level:
    avia:
      cloud:
        flight: DEBUG

