spring:
  application:
    name: "discovery"
  profiles:
    active: "default"
  config:
    import: "optional:configserver:http://localhost:8071/"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 124905365987-tk4l4gg6e2lu5kc89bpa16qjudogv6pb.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "discovery"
    description: "Avionix Discovery Application"
    version: "1.0"

logging:
  level:
    avia:
      cloud:
        flight: DEBUG
    org:
      springframework:
        security: DEBUG

