CREATE TABLE IF NOT EXISTS FAQ (
    id VARCHAR(50) PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS FAQ_CONTENT (
    id VARCHAR(50) PRIMARY KEY,
    faq_id VARCHAR(50) REFERENCES FAQ(id) ON DELETE CASCADE,
    question TEXT,
    answer TEXT,
    lan VARCHAR(2)
);
CREATE TABLE IF NOT EXISTS SKYLINE_BENEFITS (
    id VARCHAR(50) PRIMARY KEY,
    created_at TIMESTAMP,
    created_by VARCHAR(50),
    updated_at TIMESTAMP,
    updated_by VARCHAR(50),
    logo BYTEA
);
CREATE TABLE IF NOT EXISTS SKYLINE_BENEFITS_CONTENT (
    id VARCHAR(50) PRIMARY KEY,
    skyline_benefits_id VARCHAR(50) REFERENCES SKYLINE_BENEFITS(id) ON DELETE CASCADE,
    title TEXT,
    description TEXT,
    lan VARCHAR(2)
);
CREATE TABLE IF NOT EXISTS PRIVACY_POLICY (
    id VARCHAR(50) PRIMARY KEY,
    created_at TIMESTAMP,
    created_by VARCHAR(50),
    updated_at TIMESTAMP,
    updated_by VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS PRIVACY_POLICY_CONTENT (
    id VARCHAR(50) PRIMARY KEY,
    privacy_policy_id VARCHAR(50) REFERENCES PRIVACY_POLICY(id) ON DELETE CASCADE,
    title TEXT,
    description TEXT,
    lan VARCHAR(2)
);
CREATE TABLE IF NOT EXISTS TERMS_OF_USE (
    id VARCHAR(50) PRIMARY KEY,
    type VARCHAR(10),
    created_at TIMESTAMP,
    created_by VARCHAR(50),
    updated_at TIMESTAMP,
    updated_by VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS TERMS_OF_USE_CONTENT (
    id VARCHAR(50) PRIMARY KEY,
    terms_of_use_id VARCHAR(50) REFERENCES TERMS_OF_USE(id) ON DELETE CASCADE,
    title TEXT,
    description TEXT,
    lan VARCHAR(2)
);
CREATE TABLE IF NOT EXISTS CONTACT (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(50),
    email VARCHAR(50),
    message TEXT,
    created_at DATE
);

